### ISSUE TITLE
Decide on venue and date

### ISSUE THREAD

**Issue by BrunoGrandePhD** [hackseq/hackseq_2017#1]

**Comment by adrisua** [comment]
@hackseq/steering_committee Here is the contact info for ECOSCOPE's program coordinator:
Mandeep Nahal <mandeep.nahal@ubc.ca> 604 827 4216
The best would be to ask her (preferably from a ubc email account) if they would like to support hackseq once more (in-kind donation). If they say yes, you could then send her a set of dates to check the availability of the Atriums at LSI :)

**Comment by Phillip-a-richmond** [comment]
I'm thinking that LSI is ideal, and date-wise I think if we focus on some time in the Fall again that would be the best.  It would give us enough time and ensure that lots of people are around (since Summer often has a lot of traveling involved).

Also agree that doing a Friday-Saturday-Sunday is a good 3 day period, with a soft-start on Thursday.

**Comment by dfornika** [comment]
Can I just poke this issue a bit? Has someone taken on the task of contacting ECOSCOPE?

**Comment by jasgrewal** [comment]
I can reach out to ECOSCOPE, but I was hoping to meet and determine an ideal range of dates that I can inquire about specifically first?

**Comment by lfunderburk** [comment]
I agree to focus on sometime in the Fall term. Sometime October perhaps? 

We would be looking at:

- Friday 13th - Sunday 15th
- Friday 20th - Sunday 22nd
- Friday 27th - Sunday 30th

There is a long weekend from Saturday 7th to Monday 9th but I am worried people might have long weekend plans - hence I suggested the above dates.

**Comment by adrisua** [comment]
FYI I will be away from March 20th to April 10th. If you have questions or need information please let me know before then.

**Comment by jasgrewal** [comment]
Sent out an email today to Mandeep, will update whenever she replies.

**Comment by jasgrewal** [comment]
Moved to https://github.com/hackseq/hackseq_2017/issues/9
