### ISSUE TITLE
Schedule Next Meeting

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#10]
Hey, as discussed in the meeting yesterday, we should have another meeting with ideas about our roles. Here's the Doodle: http://doodle.com/poll/fzwa4nx8eabs634t

The plan would be 6:30pm again at the Genome Sciences Centre (Smith Room). If another time or location is preferable, add a comment and we can figure it out.

**Comment by jakelever** [comment]
Hey, paging @viennalam , @csiu and @lfunderburk . Could you guys fill in the Doodle?

Vienna, do you want to Skype in again?

**Comment by lfunderburk** [comment]
Hello all!

I depart to Germany on April 2. I can do meetings either really late at night - 9pm or 10 pm - or really early - 6 am , 7 am or 8 am-  (Vancouver time ).

I am under the impression this would not work with the current schedule. Can we figure out a way so that I can be posted and also chip in where it is needed?

**Comment by jakelever** [comment]
Hey all, looks like the next meeting will be April 11th. Sorry to those that can't make it. Let us know if you'd like to Skype in.

@lfunderburk , have a great time in Germany! We could move the meeting to a late evening meeting (i.e. around 9pm). What do people think?

**Comment by jasgrewal** [comment]
Fine by me, I don't have any plans that night so 9 PM works too.

**Comment by csiu** [comment]
9 PM is kind of late :(

**Comment by jakelever** [comment]
Hey, for the meeting time, I think we should maybe keep it at 6:30pm for now. Sorry @lfunderburk . I posted the [minutes from the last meeting](/hackseq/hackseq_2017/blob/master/organization/meeting_minutes/2017-03-14_committee_minutes.md). And will of course post the next ones.

We agreed our roles more formally in the last meeting and agreed to go away and come up with a plan for our role. Are you still good to work on the website? If so, you could send a short text on your plans for the website and any questions that you'd like answered (or help needed). How does that sound?
