### ISSUE TITLE
Agenda for April 11th Meeting

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#12]
Hey, the next meeting is scheduled for Tuesday, April 11th at 6:30pm in the Smith Room at the Genome Sciences Centre. This issue is to create an agenda for the next meeting.

**Comment by jasgrewal** [comment]
I'll be giving an update on the LSI bookings and security booking requirements.

**Comment by lchong** [comment]
I'll update on computational requirements and possible solutions.

**Comment by jakelever** [comment]
One of Dan or I will give an update on the fundraising planning.

**Comment by csiu** [comment]
I'll give an update on leader recruitment
- process last year
- discussion what we should do this year

**Comment by jakelever** [comment]
Also we should discuss a few roles that may should be filled: (taken from #3)

- Team leader recruitment (it sounds like @viennalam won't be able to help with this as this needs to start now. So @csiu might need someone else to help with this)
- Watching the Gmail account
- Managing the budget and dealing with expenses (do we have someone for that at the moment?)

**Comment by jakelever** [comment]
Added the [minutes from this meeting](https://github.com/hackseq/hackseq_2017/blob/master/organization/meeting_minutes/2017-04-11_committee_minutes.md)
