### ISSUE TITLE
Agenda for May 9th Meeting

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#15]
Hey all, the next meeting for the organising committee will be Tuesday May 9th at the Genome Sciences Centre at 6:30pm. This issue is to add things for discussion.

@lfunderburk , is there anything that should be discussed for the website? Or any other info you need?

And sorry @dfornika that this is scheduled when you can't make it.

**Comment by lfunderburk** [comment]
Unfortunately I misplaced the login information to the website that Artem had given me. It is possible to ask Artem:

1) URL to editing wesbite
2) Login credentials
3) PDF containing design outline

If privacy is an issue, this information can be sent to my current email address lgutierr@sfu.ca. Previously it had been sent to my bccrc.ca account, but since my username expired on May 1st and I did not do a backup I cannot access it anymore.

Thank you

Laura

**Comment by jasgrewal** [comment]
Hi @lfunderburk , you can find the login details and the design outline [here](https://github.com/hackseq/hackseq_2017_Private/tree/master/website)

**Comment by jakelever** [comment]
For the agenda:
- Plan for announcement at VanBUG
- Report on progress of community partners / sponsors hunt

**Comment by abaghela** [comment]
Hey guys, 
Would it be possible to Skype in for tomorrows meeting? I don't think I will be able to make it to UBC/Vancouver tomorrow, sorry. 
 Thanks

**Comment by jakelever** [comment]
Let's try using the phone in the conference room instead of my laptop this time. I think the sound will work better. @abaghela Want to send me an email with your cell number and we'll call you at the beginning of the meeting?

**Comment by jakelever** [comment]
Another item for the agenda
- Collaboration with the Student Biotechnology Network (thesbn.ca), possible social and announcement/info at the SBN/Genome BC research day (http://thesbn.ca/Events/2016-17/poster-competition-2017)

**Comment by jakelever** [comment]
- Clarify who is contacting SCWIST. @dfornika has contact details. Was @abaghela also going to be making contact? It'd be good to get them officially as "Community Partners"

**Comment by jakelever** [comment]
Minutes are posted: https://github.com/hackseq/hackseq_2017/blob/master/organization/meeting_minutes/2017-05-09_committee_minutes.md
