### ISSUE TITLE
Closer to Hackseq ToDo list

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#16]
Hey, I thought I'd start a single issue where we can note ideas of tasks that need to be completed closer to the hackseq event. This way, we can keep our plans organised and don't forget any single task when things get hectic during the summer and fall. These should all be things that we need to deal with in later summer (e.g. August onwards).

To start off with:

- Contact the UBC newspaper (Ubyssey) - see the private repo for Artem's Ubyssey contact
- Contact other journalists too
- Media release forms?. Are these required so that we can use photos from hackseq17 later?
- Put together a schedule of events for participants

**Comment by abaghela** [comment]
I think my friend Nivi is the Science editor at the Ubyssey now! I can talk to her about getting something out about us!

**Comment by jasgrewal** [comment]
bumping this. Are we discussing this at the next meeting
