### ISSUE TITLE
Website updates

### ISSUE THREAD

**Issue by jasgrewal** [hackseq/hackseq_2017#17]
Thread to track any updates that need to be made to the website

**Comment by jasgrewal** [comment]
@lchong @csiu @abaghela Please take a look at the participation links and landing page [here](https://hackseq-collective.squarespace.com) and let me know if anything needs tinkering! The participants go to a separate excel sheet in the google drive, and the team lead signups go to a separate one.

**Comment by jasgrewal** [comment]
For team leads - Submission button links to the Google Form
For participants - Google Form built separate, has website form. I say in the website form that we will get in touch with them closer to October once we have our project ideas lined up.

**Comment by abaghela** [comment]
I think it looks great @jasgrewal I can tweet about it!

**Comment by jasgrewal** [comment]
Great! Also, posted the wrong link earlier, the correct public facing side will be www.hackseq.com @abaghela

**Comment by jasgrewal** [comment]
Schedule is up at http://www.hackseq.com/schedule 
Could everyone please look at it and approve before I make a hard link to it from the landing page? @jakelever @abaghela @dfornika @lchong @csiu  
Also, will need the link to the volunteer recruitment form, before 5 PM tomorrow if possible, @lchong @csiu, so I can add it to the VanBUG announcement.

**Comment by lchong** [comment]
@jasgrewal looks good to me!

Here's the form: https://goo.gl/forms/36X5fLqxYmoXbX4N2

I'll send the emails to the mailing list and Sharon tomorrow.

**Comment by dfornika** [comment]
Looks great!

**Comment by lchong** [comment]
@jasgrewal Just noticed that the schedule for the final day has hacking until 16:30 but it should be only until 16:00.
