### ISSUE TITLE
Schedule next meeting

### ISSUE THREAD

**Issue by BrunoGrandePhD** [hackseq/hackseq_2017#2]
Update title once date and time is settled.

**Comment by jakelever** [comment]
Hey all, I plan to schedule the next meeting soon. I would propose to meet again at the GSC at 6pm after work. Before I set up the Doodle, are there any other suggestions for venue/time? i.e. meeting at UBC or later in the evening or on the weekend.

**Comment by dfornika** [comment]
Slightly later (6:30) would work better for me, just to give me a bit more travel time to get out from SFU if I'm stuck at work a bit past 5.

**Comment by jasgrewal** [comment]
I'm good with 6/6:30 PM onwards at the GSC. As per availability, this week is a bit tight (I can make it Tuesday at 6:30, or a bit earlier on Friday), and next week anytime besides the 8th/9th or March.

**Comment by Phillip-a-richmond** [comment]
My availability opens way up starting March 10th, and evenings at GSC is good for me.

**Comment by jakelever** [comment]
Hey all, here is a Doodle for the next meeting: http://doodle.com/poll/yhccgc25rm2zp48b

The plan would be 6:30pm at the GSC. I've put the dates a couple weeks a way as it sounds like a few people are rather busy at the moment.

**Comment by jakelever** [comment]
Hey, could @abaghela and @lfunderburk fill out the Doodle when you get the chance?

**Comment by jakelever** [comment]
It looks like everyone can make March 14th. So we'll meet at the GSC at 6:30pm next Tuesday in the Smith Room (by reception).
