### ISSUE TITLE
Agenda for June 13th meeting

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#21]
Hey all, here's the ticket for agenda items for the Hackseq meeting tomorrow. Again, it will be hosted at 6:30pm (June 13th) at the Genome Sciences Centre.

- Confirm sponsorship levels (Github & ECOSCOPE)
- Update on sponsorship
- Discussion on proposed projects and next steps

**Comment by jakelever** [comment]
@jasgrewal I have this vague memory that you had taken minutes for this but I could be completely mistaken. Is that the case? Or should I write up what I've got?

**Comment by jasgrewal** [comment]
Oops missed this as I was on the road @jakelever . I can add these later today.
