### ISSUE TITLE
Organise July Meeting

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#22]
Hey all, apologies that this is very late. I'm still in Scotland and won't be back for a few weeks. Jasleen is also away. So at the moment, a new venue may need to be found.

So we'll stick to 6:30pm after work, but a venue is undecided. Any suggestions?

And the Doodle: https://doodle.com/poll/4bvak54n9s2bpfhr

**Comment by abaghela** [comment]
Any coffee shop on Broadway is fine with me.

**Comment by jakelever** [comment]
Hey @lchong and @csiu , just a poke to fill out the Doodle.

**Comment by jakelever** [comment]
Hey, the Doodle has spoken. The meeting will be on July 20th at 6:30pm. I will be back then so we could host it in the GSC again. Sorry @csiu, any chance you can make it?

**Comment by csiu** [comment]
I'll try to make it

---
*Celia Siu*
MSc Computational Biology | UBC
LinkedIn: https://www.linkedin.com/in/celiasiu
Blog: http://csiu.github.io/blog/

**Comment by jasgrewal** [comment]
Oh damn guys I totally mixed up the time zones. So sorry to have missed this! No major updates from my end though. I'll see you all in August <3
