### ISSUE TITLE
Agenda for July 20th meeting

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#23]
Hey all, here's the ticket for agenda items for the July meeting. Please add things!

**Comment by lchong** [comment]
Shoot guys I screwed up, I can't make it on July 20th. I think based on the results the maximum number of us available is 4 so maybe we should just keep this date? My only updates are about the AWS application, and just that it's been submitted.

**Comment by lchong** [comment]
Oops nevermind -- I'll be free after all on July 20th!

**Comment by lchong** [comment]
For those who are in town, have we decided on a meeting location? We can probably do it at the CRC, I can let people in if they text me: (416) 527-3989
@dfornika @csiu @abaghela

**Comment by abaghela** [comment]
Hey guys, 

I have this GSS meeting that I might need to attend. Sorry I kind of forgot it was this week. Since Jasleen, Jake, maybe me, and maybe celia are not attending, can we just chat over Whatsapp? Or slack? And fill each other in on what we are doing? 

Arjun

**Comment by lchong** [comment]
Sorry for the spam but I just realized Jake mentioned in the other ticket that he's back now, and we can have the meeting at the GSC as usual. It seems like there may only be 3 of us (Jake, Dan and I) -- do we want to still meet in person or take Arjun's suggestion and just chat online? If we don't hear anything, Dan and I will show up at the GSC at 6:30pm tonight.

**Comment by jakelever** [comment]
Hey, I am back so the plan was still the GSC

**Comment by jakelever** [comment]
The [minutes are up](https://github.com/hackseq/hackseq_2017/blob/master/organization/meeting_minutes/2017-07-20_committee_minutes.md)
