### ISSUE TITLE
Ideas for hackseq 2017 sticker design

### ISSUE THREAD

**Issue by lchong** [hackseq/hackseq_2017#25]
Artem (@ababaian) has very kindly offered to design this year's event stickers for us!

His theme will be famous band logos, so if anyone has an ideas for him please let him know in this thread.

Thanks Artem!

**Comment by lchong** [comment]
@dfornika @jakelever @jasgrewal @abaghela @csiu

**Comment by dfornika** [comment]
How about

```
===
RUN
DNA
===
```

**Comment by csiu** [comment]
Where did "run" come from? :smile:

**Comment by jakelever** [comment]
![Run DMC](https://upload.wikimedia.org/wikipedia/fi/thumb/4/4c/Runlogo.png/240px-Runlogo.png)

**Comment by ababaian** [comment]
So while not totally obvious, the hackseq logo is an homage to Black Flag, so to keep up the theme I'll make a few sticker designs and maybe we can print 2-3 of them as little tokens' for participants. It's a little thing and it costs about $80 for the sets of stickers.

I can do RUN DMC @dfornika.

So far I have Daft Punk drafted up, I can make it a bit nicer.

![Daft Punk](https://github.com/hackseq/hackseq_2017/blob/master/organization/stickers/hs17_daft_punk_draft.png)

**Comment by ababaian** [comment]
OK gang, I've got 4 ideas so far. I've expanded to Album Covers as well, so if you can think of an iconic album cover which would look cool 'retooled' for biology let me know and I'll try my hand at it. 

**Daft Punk**
![Daft Punk](https://raw.githubusercontent.com/hackseq/hackseq_2017/master/organization/stickers/hs17_daft_punk_draft.png)

**Macintosh Plus**
![Macintosh Plus](https://github.com/hackseq/hackseq_2017/raw/master/organization/stickers/hackintoshplus.png)

**Run DMC**
![Run DMC](https://github.com/hackseq/hackseq_2017/raw/master/organization/stickers/rundmc.png)

I think the best idea I've had is **Joy Division**, but using RNAseq/ChIPseq traces. The original album cover is based on the diagram from the discovery of Pulsars which is really cool. This one is taking more effort though to get to look nice.

The original Joy Division Album cover:
![Joy Division](http://cps-static.rovicorp.com/3/JPG_500/MI0000/019/MI0000019367.jpg?partner=allrovi.com)

**Comment by jasgrewal** [comment]
I really like the daft punk and the Joy Division ones! Super neat.

**Comment by jakelever** [comment]
I forgot to comment. They're all awesome, but I think the Daft Punk one is my favourite.

**Comment by ababaian** [comment]
![joy_division](https://user-images.githubusercontent.com/9220907/30758115-ee287d4e-9f85-11e7-9d85-36b894639660.jpg)
And here's the draft for the Joy division version. Probably my favorite, based on ChIP data around NANOG in H1 cells : )

**Comment by ababaian** [comment]
![daftpunk_large](https://user-images.githubusercontent.com/9220907/31467472-f00b16e0-ae8e-11e7-918d-2868663dce71.png)
![hs17_joyd_final_600_large](https://user-images.githubusercontent.com/9220907/31467474-f3f90a28-ae8e-11e7-8b5c-2fb6cc8aa36e.png)

I've finalized the two sticker designs: Joy Division and Daft Punk. Would you all like to decide which (if any) to go with? 

I recommend 2 inch square with round corners so they match last years stickers. I went with [Oddball Workshop](http://www.oddballworkshop.com/) and they did a great job.

**Comment by dfornika** [comment]
They both look awesome. I think we should print up both of them.

**Comment by abaghela** [comment]
I agree, both look great and should both should be printed. Thanks for the suggestion @ababaian

**Comment by ababaian** [comment]
Are you guys going to take care of the printing or should I do it?

**Comment by abaghela** [comment]
I can take care of it @ababaian. Im in contact with Oddball currently. Thanks for the designs and suggestion!
