### ISSUE TITLE
Agenda for August 14th meeting

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#26]
Hey all, the next meeting will be on Monday August 14th at 6:30pm at the Genome Sciences Centre. This issue is for agenda items for the meeting.

**Comment by jakelever** [comment]
A few agenda items

- Update on sponsorship
- I will be away in DC
- Update on Google contact

**Comment by jasgrewal** [comment]
I'll be giving an update on the participant form at the website, and the update on the internet at UBC as I don't think I've updated everyone in the team on that yet.

**Comment by jakelever** [comment]
Also

- NumFocus sponsorship
- Code of Conduct

**Comment by jakelever** [comment]
Hey all, I've typed up the [minutes](https://github.com/hackseq/hackseq_2017/blob/master/organization/meeting_minutes/2017-08-14_committee_minutes.md).

@jasgrewal , @dfornika , @lchong , @abaghela There are a lot of action items (i.e. things that people have agreed to do). Please check to see what I noted done and update the minutes if you think I missed anything.
