### ISSUE TITLE
URGENT: Add Git lesson question to participant recruitment

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#28]
Hey @jasgrewal ,

Could we add the following question to the participant recruitment before too many people sign up?

"Would you be interested in a short tutorial on using Git and Github on the evening of October 19th on campus at UBC? That's the night before hackseq starts. You'd get to meet other participants and get comfortable with Git and learn from an amazing Software Carpentry instructor."

**Comment by jasgrewal** [comment]
In a meeting atm, I'll fix this in half an hour

**Comment by jasgrewal** [comment]
done

**Comment by jakelever** [comment]
Nice one
