### ISSUE TITLE
Schedule September Meeting

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#29]
Hey all, here's the Doodle for the September meeting. It would again be 6:30pm in the Genome Sciences Centre (570 W 7th). I definitely won't be there (and won't be back in Vancouver until late September). So it'd be up to Jasleen to make sure that you can get into the building. Or you could hold it somewhere else if preferred. Anyway, the Doodle awaits:

https://doodle.com/poll/66v97ce5igau7kga

**Comment by jasgrewal** [comment]
Yep, we can have it at the GSC. Thanks for setting up the poll, Jake!

**Comment by jasgrewal** [comment]
Nudging @lfunderburk @abaghela @dfornika for the doodle :P

**Comment by jasgrewal** [comment]
Looks like majority vote is for September 12th, Tuesday. See you all then! Cheers :)

**Comment by jakelever** [comment]
Excellent. I'll make the agenda issue
