### ISSUE TITLE
Assign roles

### ISSUE THREAD

**Issue by BrunoGrandePhD** [hackseq/hackseq_2017#3]

**Comment by jakelever** [comment]
It'd probably be a good idea to restate what we said at the meeting about which roles we'd be willing to do.

I'd be willing to work with Dan on some of the logistics (e.g. venue / fundraising). And I'd also be happy to take on the role of secretary to make sure we have meetings with agendas and minutes.

**Comment by dfornika** [comment]
These are the roles that I've got from my notes from the last meeting (may not be completely accurate, speak up if I misunderstood):

Laura (@lfunderburk): Website & Graphic Design
Dan (@dfornika): Fundraising & Budgeting
Jasleen (@jasgrewal): Venue, Website & Technical Support
Jake (@jakelever): Logistics & Fundraising
Arjun (@abaghela): Social Media & Recruitment, Venue Booking, Setup, Food
Lauren (@lchong): Technical Support
Vienna (@viennalam): 
Celia (@csiu): Leader recruitment

**Comment by dfornika** [comment]
@jakelever I've typed up my notes from the last meeting and dropped them in this repo. Feel free to edit them and move them somewhere else.

**Comment by jasgrewal** [comment]
@dfornika Awesomesauce, thanks for sharing that! Sounds good to me :)

**Comment by Phillip-a-richmond** [comment]
I'll work on Recruitment and Technical support.  My involvement in ARC and collaborations with WestGrid and ComputeCanada should be a help with both of those roles.  I can also help when it comes to doing food runs on the day of the event.

**Comment by abaghela** [comment]
Hey, this looks good to me too. I can also help with venue booking/set-up/food, but social media and recruitment is great. Thanks!

**Comment by lfunderburk** [comment]
Yay! Go Team!

**Comment by Brittdrog** [comment]
For whoever takes on the Team Leader recruitment role, here are some [email drafts](https://drive.google.com/drive/folders/0B4gAe5f4VChNOExqYzk5Z1dndjQ) and [application forms](https://github.com/hackseq/October_2016/blob/master/Forms.md) from hackseq16, which may be of use

**Comment by viennalam** [comment]
Hello, 

Should I just be a floater until the summer? I'm definitely happy to help do the setup and be there to help during the event. 

Kind regards, 
Vienna

**Comment by jakelever** [comment]
Hey Vienna, from the last meeting I think you said you'd be up for helping with team leader recruitment with Celia ( @csiu ). Is that right?

**Comment by viennalam** [comment]
Hello Jake, 

I don't recall, but yes, I am happy to help in Fall. If the team needs someone that is available throughout the coordination and planning process of this event, I should probably excuse myself right now because I don't want to drop-the-ball. I am happy to help out during the actual event as well as a volunteer. 

Also, I looked at the doodle calendar, and unfortunately will be in the field and won't have a stable internet connection for Skype. Thank you for including me though! 

Please let me know, 
Vienna

**Comment by jakelever** [comment]
A few thoughts on roles that need filling or more people:
- Team leader recruitment (it sounds like @viennalam won't be able to help with this as this needs to start now. So @csiu might need someone else to help with this)
- Watching the Gmail account
- Managing the budget and dealing with expenses (do we have someone for that at the moment?)
