### ISSUE TITLE
Agenda for September 12th meeting

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#30]
This is the agenda issue for the Tuesday September 12th meeting (6:30pm at the GSC). Contact Jasleen to get access to the building.

**Comment by jakelever** [comment]
Hey, I won't be making this meeting. So here's an update from me:

- Sponsorship
   - Lunch sponsorship (for first lunch) from Chipotle is confirmed
   - Otherwise no new sponsorships since last meeting
   - Some potential food sponsors (e.g. Safeways) suggests getting in contact directly with store managers. Would anyone be willing to do this? This kinda requires actually being in Vancouver
   - Applied for funding from AMS (Student Initiative Fund) and UBC (Walter H Gage Memorial Fund). Walter Gage has responded that we need to be associated with an official UBC organisation or faculty. So that probably won't go anywhere, unless we think we could get a department associated with it.
- Community Partners
   - I contacted all our community partners to get the word out about participation recruitment
   - I also contacted several Women in Science groups in Vancouver, Seattle & Portland to get them to forward the info
   - I may have also asked Jenny Bryan, Hadley Wickham and a few others to tweet about it. This may be the reason that we have more virtual participants.

So a few ideas for agenda items:
- Plans for Virtual Participation
   - Do we assign them evenly across teams, or do specific virtual teams
   - Could we find a project that is suitable for a virtual team (e.g. lots of small components that can be done individually easily)?
   - What technology should we recommend for teams? e.g. Slack obviously, but hangouts, skype, etc? Maybe a tool for project management so members can understand the overall task and see what subtasks are assigned/unassigned?
- Participant recruitment
   - What do we need to do when recruitment closes?

Also please remember to take minutes and upload them

**Comment by jasgrewal** [comment]
Thanks @jakelever. Also, it seems like @abaghela cannot make it tomorrow either. Can @csiu @dfornika and @lchong  please confirm they'll be around? We will primarily need to brainstorm the virtual participation business, I'll hack together a formal agenda prior to the meeting tomorrow.

**Comment by lchong** [comment]
I'll be there! I'll give an update on the technical resources for the event.

**Comment by dfornika** [comment]
I can be there.

**Comment by jakelever** [comment]
Hey, two more things:
- We just this minute got funding from the AMS Student Initiative Fund. Yay! That's for $500. I think we claim the money back through receipts after the event but will confirm.
- We should probably send someone to VanBUG (Sept 21st) as a last minute advertisement for hackseq participant recruitment. Is anyone willing to do that? (I would be won't be back until the 28th).

**Comment by jasgrewal** [comment]
Meeting Agenda | Tuesday, September 12th, 2017 | Genome Sciences Centre, 6:30 PM 
_Attending: Jasleen, Lauren, Celia, Dan  
Regrets: Jake, Arjun_

**UPDATES**
_Update from Jake_
- Confirmed AMS Student Initiative Fund ($500, claimable after the event? TBC)
- Confirmed Chipotle sponsorship for 1 lunch
- Community partners have been alerted to notify participant recruitment

_Update from Dan_

_Update from Jasleen_
- Potential collaborative event with Bioinformatics Department on October 21st evening (prior to HackSeq kick-off)
- Update on AMS sponsorship for food

_Update from Lauren_
- Technical resources

**Issues for Discussion**
- Any update on the Lumohacks discussion?
- Assignment of participants to projects after September 22nd (Friday, organize meeting on September 25/26?)
- Management of Virtual Participants
  - Suggestions include single project being done virtually, vs spread them across teams (virtual modules?), 
  - Also need to determine modes of communication for virtual participants + using project managment tools
  - Should we be getting in touch with team leads interested in managing a virtual team simultaneously?

**Action Items**
- Shout-out person for the VanBUG talk (September 21st)
- Contact store managers for potential food sponsors (Safeway, Save On etc)
- Send email to AMS VP Admin for potential food sponsorship
- [Jasleen] Send letters to Starbucks and Tim Hortons
- [Jasleen] Confirm UBC Security and UBC IT for the event
- [Lauren] are we able to use Docker within the Orca Dockers (Project 2)

**Comment by jasgrewal** [comment]
Meeting minutes are [up](https://github.com/hackseq/hackseq_2017/blob/master/organization/meeting_minutes/2017-09-12_committee_minutes.md). Please look at the different TO-DOs for followups from each person, comment here if any questions/replies!

**Comment by jasgrewal** [comment]
Specific action items summarized for ease:
- Need to set up a Facebook event page for promotion and recruitment @abaghela 
- Do we have a prepared slide to use for the shoutout at Vanbug @jakelever 
- Do we need more participants or are we at a good number @lchong 
- Where will the closing social be, and what are the costs @jasgrewal
- What's entailed in following up with store managers for food sponsorship? Any thoughts we can base off of, @jakelever ?
- Setting up the new slack channel / reusing the old one. This has to be split by projects at some level @lchong 
- Contacting team leads for interest in virtual participants (refer to minutes for benefits to be listed + note time differences can make an impact on participation) @lchong 
- Any expenses for ORCA last year? @lchong will check budget.  
- Following up on AWS application status @lchong 
- Any update on Google Cloud contact for sponsorship @dfornika ? 
- Following up on [private issue on food sponsorship](https://github.com/hackseq/hackseq_2017_Private/issues/31) @dfornika and @jasgrewal

**Comment by jakelever** [comment]
Hey, I'll send round the slide that I used for VanBUG for team leader recruitment. It will only require a minor change. Who is going to speak? Will Hsiao hasn't got back to me about this. So you'd need to contact him again and confirm.

And for food, I think you basically walk into the store and ask to talk to the manager or for his/her contact details. Be ready with a short pitch or drop them an email if they're not available. Most stores do a fair amount of community sponsorship so they shouldn't be surprised by the idea. Emphasis our aim of improving diversity in science.

**Comment by lchong** [comment]
Some answers to action items (I'll update this comment with more answers later):

-Just counted the desired team sizes in the applications, and the total is ~55 participants, so I think we're on pace for that already (assuming all team leads are okay with some virtual participants)
-Nothing in last year's budget about a cost for using ORCA, but I'll verify at my next meeting with the team

**Comment by abaghela** [comment]
OK facebook page done. I will do a project highlight thing in the next couple days. My facebook network/usage is next to non-existent, so please like the page. hackseq needs Instagram and snapchat :P

**Comment by jakelever** [comment]
Hey, just checking. Has anyone managed to get in contact with Will Hsiao (or other VanBug people) to confirm whether we can talk on Thursday?

**Comment by dfornika** [comment]
I'll talk to him today.

**Comment by dfornika** [comment]
I got confirmation that we can do a brief announcement on Thursday.

I was planning on going to VanBUG anyways so I'm available to do the announcement.
