### ISSUE TITLE
Agenda for September 26th meeting

### ISSUE THREAD

**Issue by jasgrewal** [hackseq/hackseq_2017#31]
The aim of this meeting is to review participants, assign them, and have notifications for assignment sent out to them by the end of the week (September 29th). Dan, Lauren, and Jasleen have already confirmed attendance. @abaghela and @csiu please rsvp. @jakelever assuming you'll still be rolling with the bigwigs around then. 
6:30pm at the GSC, contact Jasleen for building access.

**Comment by jakelever** [comment]
Yep, I won't be back in Vancouver until the 29th ish.

**Comment by abaghela** [comment]
I will be there

**Comment by dfornika** [comment]
I'll be there.

**Comment by csiu** [comment]
Adding date to calendar ... I'll be there

**Comment by lchong** [comment]
@jasgrewal We received one response from the participants we emailed saying that he will be virtual. I think this is probably enough to surmise that all 3 of them will be virtual. So it's probably safe to update that and email the team leads now!

Let me know if you want any help adjusting the participant allocations.

**Comment by jasgrewal** [comment]
meeting minutes will be up over the weekend!

**Comment by jasgrewal** [comment]
Meeting minutes [are up](https://github.com/hackseq/hackseq_2017/blob/master/organization/meeting_minutes/2017-09-26_committee_minutes.md)
