### ISSUE TITLE
ORCA setup

### ISSUE THREAD

**Issue by lchong** [hackseq/hackseq_2017#33]
@tmozgach @sjackman 

Hi all, we can use this issue to centralize the conversation about ORCA software installations prior to the event. Here are the requests from team leaders so far:

# Project 2

See issue for full discussion (https://github.com/hackseq/hackseq_projects_2017/issues/2)

- [x] methpipe

# Project 6

- [x] Bedtools
- [x] BWA
- [x] FastQC
- [x] Graphviz
- [x] ~~Long Ranger~~ license prevents redistribution
- [x] LRSIM
- [x] makefile2graph
- [x] Miller
- [x] R
- [x] RStudio Server
- [x] samtools
- [x] seqtk

# Project 8

- [x] scikit-learn
- [x] pytorch

# R Packages

+ [x] Bioconductor
+ [x] `data.table`
+ [x] `devtools`
+ [x] `DiagrammeR`
+ [x] `doMC`
+ [x] `DT`
+ [x] `fuzzyjoin`
+ [x] `ggplot`
+ [x] `igraph`
+ [x] `knitr`
+ [x] `pander`
+ [x] `revealjs`
+ [x] `rmarkdown`
+ [x] `roxygen2`
+ [x] `tidyverse`

+ [x] phytools

I'll follow up shortly with the leaders to remind them to put together their lists.

**Comment by sjackman** [comment]
@tmozgach Please `brew install graphviz lrsim makefile2graph`
`rstudio-server` has two open issues: https://github.com/Homebrew/homebrew-science/pull/5502 and https://github.com/Homebrew/homebrew-science/pull/6315

**Comment by BrunoGrandePhD** [comment]
What packages are installed for R? Since installing several R packages on Linux can take a while due to compilation, it would help if a few main ones come pre-installed. I've put together an initial list below, but it might get longer after discussing more specific goals with team members. 

## R Packages

- [ ] `tidyverse`
- [ ] `rmarkdown`
- [ ] `DT`
- [ ] `fuzzyjoin`
- [ ] `pander`
- [ ] `doMC`
- [ ] `revealjs`
- [ ] `devtools`
- [ ] `roxygen2`
- [ ] `data.table`

**Comment by sjackman** [comment]
There are currently no R packages installed, other than the base packages.
@tmozgach Can you please add these R packages to the ORCA image, and also `ggplot2` and `knitr`? You can install them with
```sh
Rscript -e 'install.packages(c("tidyverse", …, "data.table", "ggplot2", "knitr"))'
```
and Bioconductor, using these instructions: https://www.bioconductor.org/install/
```sh
Rscript -e 'source("https://bioconductor.org/biocLite.R"); biocLite()'
```
Thanks!

**Comment by morien** [comment]
Will add to the list of R packages to be installed: 'phytools', plus dependencies 'ape' (>= 4.0), and 'maps'

Git, of all things, isn't on the server software list, but I have to assume it's there... (?)

**Comment by sjackman** [comment]
@morien Only those software installed by either `brew` or `pip` is listed. `git` is installed by `apt-get` and so isn't included in this list.

**Comment by sjackman** [comment]
@tmozgach Please add `igraph` and `DiagrammeR` to the list of R packages.

**Comment by morien** [comment]
@sjackman ah okay, well then we can strike "tree" from the list of requests, that would also get installed with the OS package manager, not brew or pip

**Comment by sjackman** [comment]
The Docker image that we're using is `bcgsc/orca:2017.08.23` which is based on `linuxbrew/linuxbrew:1.2.8` which is based on `ubuntu:trusty`. The next release of ORCA will be based on `linuxbrew/linuxbrew:1.3.*` and `ubuntu:xenial`. Feel free to check it out if you'd like to poke around and see what software is installed, and try out your pipeline prior to Hackseq. Note that the image is 10 GB.

**Comment by lchong** [comment]
From **Project 8**: "Could we get scikit-learn and pytorch preinstalled on our ORCA machines?"

- [ ] scikit-learn
- [ ] pytorch

**Comment by sjackman** [comment]
@tmozgach I've added the software listed in the comments above the to the summary of this issue:
https://github.com/hackseq/hackseq_2017/issues/33#issue-260371673
Can you please tick off the boxes that you've installed in the ORCA image?

**Comment by sjackman** [comment]
@lchong Could you please add Tanya @tmozgach as a collaborator on this repository, so that she can tick off the boxes in the summary of this issue?

**Comment by sjackman** [comment]
@lchong Could you please send me the names and e-mail addresses of the project leads so that we can create ORCA accounts for them?

**Comment by lchong** [comment]
@sjackman try this link:

https://docs.google.com/spreadsheets/d/1IFDkStUlfCYGfYhpHPN-TYj_OxQ2LfTJ0tMC1gQZH6Y/edit?usp=sharing

**Comment by sjackman** [comment]
Thanks, Lauren!
