### ISSUE TITLE
Agenda for October 5th meeting

### ISSUE THREAD

**Issue by jasgrewal** [hackseq/hackseq_2017#34]
We will aim to outline all the housekeeping stuff, chart out the day-of plans and responsibilities, update on participant signups, tshirt order status, and media outreach. 
6:30 PM, Thursday, October 5th, at the GSC. 
Dan has sent his regrets.

**Comment by jasgrewal** [comment]
Also discuss volunteer recruitment (it appears last year it was either through mailing list or email blast as a call for volunteers, and they were quite useful especially with the food and coffee setup), and having a dedicated event photographer.

**Comment by jakelever** [comment]
Another topic: the Git tutorial. When and where to host it and who to teach it?

**Comment by jakelever** [comment]
[Minutes](https://github.com/hackseq/hackseq_2017/blob/master/organization/meeting_minutes/2017-10-05_committee_minutes.md) have been posted
