### ISSUE TITLE
Second October Meeting

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#35]
Hey, at the meeting yesterday, we suggested meeting again on Tuesday (October 10th). It'd be good to get all the organisers there.

@jasgrewal You thought you might be a bit late. Shall we do it at 7pm?

@dfornika and @abaghela can you make Tuesday?

Topics to discuss
- Food
- Volunteer Recruitment
- ORCA
- Hackseq future
- Plans for virtual participants (e.g. encourage videochat?)

**Comment by jakelever** [comment]
Hey, just pinging everyone. Are people free tomorrow night? Also happy Thanksgiving!

**Comment by jasgrewal** [comment]
Yessir, I'll be there. Happy Thanksgiving! We can probably keept it at 6:30 as the other meeting is just the first one of many, so a long agenda is highly unlikely :)

**Comment by dfornika** [comment]
Yes, I'll be there.

**Comment by abaghela** [comment]
Yeah, I will be there too.

**Comment by jasgrewal** [comment]
Some additional agenda items based on [this past issue from Hackseq 2016](https://github.com/hackseq/October_2016/issues/54) and this [logistics sheet](https://docs.google.com/spreadsheets/d/1od5J4I_Rbtqx-A4PEJOmDW7EZfqPXumYGg2iiibSv1U/edit#gid=470121124). 
- Pizza (Panago gave 20% discount last year....).
- Breakdown of breakfast items and determination of lunch items (with dietary restrictions).
- Design (black throws on the tables?).

**Comment by jakelever** [comment]
Cool. See you all at 6:30pm tonight at the GSC.

**Comment by jakelever** [comment]
Hey all, the epic [minutes](https://github.com/hackseq/hackseq_2017/blob/master/organization/meeting_minutes/2017-10-10_committee_minutes.md) for this evening are up. Please check your action items and let me know if I've missed anything.
