### ISSUE TITLE
Third October meeting

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#36]
Hey, this is the ticket for the meeting on Monday 16th October. It's at 6:30pm at the Genome Sciences Centre. Please add any agenda items here.

**Comment by jakelever** [comment]
From the Closer to Hackseq list: #16 . Do we need to do media release forms to take photos and use on the website for future promotion? Something to figure out

**Comment by jakelever** [comment]
- Should all the organisers get ORCA accounts so we can provide technical help (if we can be useful)?
- Any word from Amazon?

**Comment by lchong** [comment]
- Any new participants since last week?
- Details that haven't been passed to the team leads yet?

**Comment by jakelever** [comment]
The [minutes](https://github.com/hackseq/hackseq_2017/blob/master/organization/meeting_minutes/2017-10-16_committee_minutes.md) are up
