### ISSUE TITLE
Participant Email with Schedule, Git workshop, etc

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#37]
Hey, just planning out the email to go out announcing the schedule, Git workshop and to bring coffee mugs. The draft is below. We're still figuring out a location for the Git workshop. And are we in the West or East atrium of the LSI? Or do they have names?

@ababaian and @lchong : Want to add anything else about the schedule?
@csiu : Once we get the Git workshop location confirmed, can you email this out?

**draft:**
Dear Hackseq participants,

We hope you're getting excited for Hackseq. We certainly are. Here are four things for the upcoming event.

1. The schedule is now online at http://www.hackseq.com/schedule. The most important thing is that registration is 8-9am on Friday (Oct 20th) in the East atrium of the Life Sciences Centre at UBC. That's the big atrium with the long tables. If you're attending virtually, please be online from 9am (Pacific time) to meet your team and watch the slack #general channel for announcements.
2. We're going to have a Git workshop for those new to Git and Github. It will be at 6:30pm on Thursday 19th October on the UBC campus. It will be in room D213 of the Chemistry building. It will last about 2 hours and will be webcast too. Details (including how to get there) will be posted on the #gitworkshop Slack Channel. If you intend to come in person, please add your name to this Doodle poll: https://doodle.com/poll/ei36smhisu8pgsz4
3. There will be breakfast and lunch provided for the three days of the hackathon! We're also going to be providing coffee & tea and snacks. Please bring mugs, travel mugs, etc so we can be friendly to the environment. Note that there won't be food or drink during the Git workshop.
4. The Hackseq social will be on Saturday 21st after the hacking has finished for the day. We can head over to Mahoney's (5990 University Blvd) for some food and drinks from 6pm. Come out and meet more people from the other teams!

The only thing you need to bring is your laptop, your enthusiasm and a mug for coffee. If you've got any questions, either email us (hackseq@gmail.com) or start a discussion in the #general slack channel.

Looking forward to meeting you all,
the Hackseq Organising Committee

**Comment by ababaian** [comment]
Is food provided or should people bring?

**Comment by jakelever** [comment]
Yes, thank you for pointing this out. Breakfast and lunch are included. I will add this to the email

**Comment by jasgrewal** [comment]
@ababaian food provided oct 20-22 but not for the Git workshop (ah lol nvm I thought it was a separate inquiry)
@jakelever , the LSI East Atrium is booked for Oct 20-22,
Oct 20 - East Atrium - 730am-1030pm
Oct 21 - East Atrium - 730am-1030pm
Oct 22 - East Atrium - 730am-600pm

**Comment by jakelever** [comment]
Thanks

**Comment by jakelever** [comment]
Hey @csiu @abaghela @lchong @dfornika @jasgrewal , this email looks okay to me. Anything else we should add before sending it out?

**Comment by lchong** [comment]
@jakelever Looks great!

**Comment by dfornika** [comment]
Looks awesome to me.

**Comment by ababaian** [comment]
One more thing: Might be worth emailing the Ubyssey Science Editor: science@ubyssey.ca

They could send a reporter to come during the hackathon and interview you guys for a student story : )

**Comment by jakelever** [comment]
@ababaian Agreed, @abaghela is friends with her so will be making sure that happens

@jasgrewal Shall I add an extra point to the email specifically about the Saturday social?

@csiu What's the easiest way to email this out to all participants and team leads?

**Comment by jasgrewal** [comment]
Hi @jakelever , um sure. Still sorting out details reg food etc but we have a confirmed reservation for sure! 6 pm onwards.

**Comment by jakelever** [comment]
Cool, @jasgrewal I've added the social to the email. Look okay? And could you update the schedule so it's on the Saturday?

@csiu Can you send this email out to all team leads and participants? Remember the new additions

**Comment by csiu** [comment]
Done. I sent 3 sets of emails: 

1. In-person participants (44) - message as is
2. Virtual Participants (23) - did not mention items 3 & 4 i.e. didn't mention the food or social
3. Team leads (9)


@jakelever - The easiest way to message all participants is to BCC everyone. The mailing list I used is in the `2017 Assignments` aka `csiu's mailing list` (a new sheet that I compiled) 😓

**Comment by jakelever** [comment]
Great!
