### ISSUE TITLE
Volunteers for 2017

### ISSUE THREAD

**Issue by lchong** [hackseq/hackseq_2017#39]
@lfunderburk @viennalam Are you guys interested in helping out this weekend? If so, could you let us know your availability by filling in this form: https://goo.gl/forms/pJxv9dIBtn6pZdVn2

Thanks guys!

**Comment by lchong** [comment]
@dfornika @jakelever @jasgrewal @abaghela 
I'm going to start emailing volunteers back to schedule shifts -- any thoughts about which of the three shifts (morning/lunch/evening) we most need volunteers for?

**Comment by jasgrewal** [comment]
Morning and evening will probably be the most important, particularly evening I think. Hopefully everyone will be busy coding in the afternoon!
