### ISSUE TITLE
Recruit additional members for steering committee

### ISSUE THREAD

**Issue by BrunoGrandePhD** [hackseq/hackseq_2017#4]

**Comment by dfornika** [comment]
I've contacted Lauren Chong (Steidl Lab) to ask her about getting involved. She said she'd follow up with @jasgrewal this weekend.

**Comment by dfornika** [comment]
I've contacted Vanessa Guerra (Hart Lab, SFU + SFU Omics Group + SFU Scientific Computing Study Group) to invite her to get involved.
