### ISSUE TITLE
Hackseq Future Dinner

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#41]
Hey current and previous Hackseq organisers, this year's hackseq was a great success. We'd like to meet up and discuss the strengths and weaknesses this year and where we'd like hackseq to go in 2018. If you'd like to participate, please fill out the Doodle link below:

https://doodle.com/poll/hn8ictmpn2utd662

It'd be dinner (around 6:30pm or later if needed). Location to be decided later.

Hope you're all well. Jake

I apparently can't assign everyone so instead I'll tag everyone. If I forgot anyone, please tag them or email them.

@dfornika @csiu @jasgrewal @lchong @abaghela 
@adrisua @sjackman @Brittdrog @GalenWright @santina @ababaian @minisciencegirl @ttimbers @brunogrande @cloucks 
@hackseq/steering_committee

**Comment by jakelever** [comment]
Hey, just a poke to everyone to fill out the Doodle. Will finalise in the next couple days.

**Comment by jakelever** [comment]
Hey, the Doodle has spoken. Dinner will be next Tuesday (December 5th). Apologies to those who can't make it. 

I'll book a table for 6:30pm. It'll be at East is East on Main St (partly because we went there before and partly due to OpenTable). If anyone else would like to join, please let me know and I'll increase the reservation.

**Comment by jakelever** [comment]
Hey, just a reminder about tonight. See you later!

**Comment by sjackman** [comment]
I've double-booked myself, and I won't be able to make it. 😬 Sorry!
