### ISSUE TITLE
Introducing Vienna Chichi Lam

### ISSUE THREAD

**Issue by BrunoGrandePhD** [hackseq/hackseq_2017#6]
I just wanted to introduce Vienna Chichi Lam (@viennalam) to everyone. She has expressed interest in helping out with Hackseq. She will be busy with field work and a thesis defence over the coming months, but she said she would become available around June 15th. Be sure to loop her in around that time. Cheers!

**Comment by jakelever** [comment]
Hi @viennalam, in case you're free, we're having a meeting on Tuesday at 6:30pm at the Genome Sciences Centre (570 W 7th Ave). The agenda and minutes will be online but it'd be cool if you could come or skype into the meeting.

**Comment by viennalam** [comment]
Hello Jake, 

I finish teaching at 6:30. If it's okay for me to come in late, I'd love to join in through Skype. Is there a list of everyone's Skype address? It would be great if you could just add me to the conversation (vienna.lam@outlook.com). 

Kind regards, 
Vienna

**Comment by jakelever** [comment]
Hi Vienna, that's great! I'll bring my laptop along to the meeting and set up Skype.

**Comment by viennalam** [comment]
Great, thanks!
