### ISSUE TITLE
Agenda for March 14th meeting

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#7]
Hey, we should start putting together an agenda of what to discuss on the March 14th meeting. It's at 6:30pm at the GSC (570 W 7th Ave). Please add ideas of topics here.

**Comment by jasgrewal** [comment]
- Allocate roles and responsibilities
- Perhaps do another round of emails to UBC/SFU genomics related programs to get more volunteers?
- Determine currently available computational resources and enumerate specific compute power requirements.
- Update regarding being able to use LSI space.
- Identify fundraising sources 
- Have a github manager to look after setup of the public facing side of HackSeq 2017? 
- Outline expected Webmaster duties? (what needs to be updated on the website now, if anything, linking to twitter feed

**Comment by jakelever** [comment]
- Decide on goals for scale (e.g. ideal number of teams/participants, do we target Victoria/Seattle researchers too?)
- Plan ideas to improve diversity in participants and team-leads (or assign as task)
