### ISSUE TITLE
Confirm LSI availability

### ISSUE THREAD

**Issue by jasgrewal** [hackseq/hackseq_2017#9]
Considering weeks Oct 13-15 or Oct 20-22 (inclusive). Definitely not considering the 30th of October and neighbouring weekends on account of Halloween. 
There will be one official social, the day before (Thursday evening) or last day (Sunday night) at Gallery 2.0, ~100 people, pending availability and confirmation by @jasgrewal

**Comment by jasgrewal** [comment]
**East Atrium booking** _Awaiting Confirmation from LSI_

**Smaller room bookings** _Confirmed by ECOSCOPE_
Oct 20 - 1330 - 10am-2pm - _Boardroom style meeting room_
Oct 20 - LSC3 - _Only available after 1:30 PM, don't know if we need it then anyways_
Oct 21 - 1410 - 10am-2pm - _Classroom style meeting room_
Oct 21 - LSC 3 - 10am-2pm 
Oct 22 - 1410 - 10am-2pm
Oct 22 - LSC 3 - 10am-5pm - _Theatre style, site for closing ceremony_

**Comment by csiu** [comment]
@jasgrewal What time will hackseq start? 

(Oct 20 is a Friday and most people might be at work)

**Comment by jasgrewal** [comment]
The east atrium reservation (still awaiting official confirmation from LSI but 90% sure until then) starts at 8 am and ends by 6 pm each day. We will start registration at 8 am everyday in keeping with last years format, I imagine. I'm away from my computer until Monday so I cannot go back and check the previous year's schedule until then

**Comment by jasgrewal** [comment]
The east atrium has been confirmed. I have the confirmation and will upload it to the Drive for reference.

**Comment by jakelever** [comment]
Yay, we have a home!
